### ISSUE TITLE
ARM Outputs task has an invalid name

### ISSUE THREAD

**Issue by aholler2** [keesschollaart81/vsts-arm-outputs#28]
I'm using the new Azure Multi-Stage Pipelines experience and I believe the ARM Outputs task cannot be used because there is a space in the name.

My YAML task:
```
- task: ARM Outputs@5
          displayName: SQLServerARMOutputs
          inputs:
            ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
            ConnectedServiceNameARM: 'GIS CloudCoE POC'
            resourceGroupName: '${{ parameters.resourceGroupName }}'
            whenLastDeploymentIsFailed: 'fail'
            deploymentNameFilter: 'sql-server-w-database*'
```

My error(s) (multiple attempts):
`20190625.19: "Job Job1: Step ARM Outputs has an invalid name. Valid names may only contain alphanumeric characters and '_' and may not start with a number."`

`20190625.20: "Job Job1: Step keesschollaart.arm-outputs.arm-outputs.ARM Outputs has an invalid name. Valid names may only contain alphanumeric characters and '_' and may not start with a number."`

**Comment by aholler2** [comment]
I've resolved this issue. The easy fix is to add the literal keyword 'name' as such:
```
- task: ARM Outputs@5
          displayName: SQLServerARMOutputs
          name: ARMOutputs
          inputs:
            ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
            ConnectedServiceNameARM: 'GIS CloudCoE POC'
            resourceGroupName: '${{ parameters.resourceGroupName }}'
            whenLastDeploymentIsFailed: 'fail'
            deploymentNameFilter: 'sql-server-w-database*
```
